[package]
name = "pyline-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
pyline-libs = {path = "../pyline-libs"}
clap = { version = "4.5.53", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }

[[bin]]
name = "pyline"
path = "src/main.rs"